<% require './lib/extjs_autodep' %>
---
gzip_assets: off
allow_debugging: off
compress_assets: false
stylesheets:
  common:
    - public/stylesheets/grid.css
    - public/stylesheets/application.css
    - public/extjs/examples/ux/**/*.css
  ie:
    - public/stylesheets/grid_ie.css

javascripts:
  common:
    - public/javascripts/application.js
    - public/javascripts/extjs_hacky_monkey_patches.js
  extjs_autodep: <%= ExtjsAutodep.as_yaml %>
