---
gzip_assets: off
allow_debugging: off
stylesheets:
  common:
    - public/stylesheets/grid.css
    - public/stylesheets/application.css
  ie:
    - public/stylesheets/grid_ie.css

javascripts:
  common:
    - public/javascripts/application.js
    - public/javascripts/extjs_hacky_monkey_patches.js

    - public/javascripts/Imits/data/JsonWriter.js
    - public/javascripts/Imits/data/JsonReader.js
    - public/javascripts/Imits/data/Proxy.js
    - public/javascripts/Imits/model/MiPlan.js
    - public/javascripts/Imits/model/MiAttempt.js
    - public/javascripts/Imits/model/PhenotypeAttempt.js
    - public/javascripts/Imits/model/Gene.js
    - public/javascripts/Imits/widget/Window.js
    - public/javascripts/Imits/widget/Grid.js
    - public/javascripts/Imits/widget/SimpleNumberField.js
    - public/javascripts/Imits/widget/SimpleCheckbox.js
    - public/javascripts/Imits/widget/SimpleCombo.js
    - public/javascripts/Imits/widget/QCCombo.js
    - public/javascripts/Imits/widget/grid/BoolGridColumn.js
    - public/javascripts/Imits/widget/grid/SimpleDateColumn.js
    - public/javascripts/Imits/widget/grid/RansackFiltersFeature.js
    - public/javascripts/Imits/widget/grid/MiAttemptRansackFiltersFeature.js
    - public/javascripts/Imits/widget/grid/MiPlanRansackFiltersFeature.js
    - public/javascripts/Imits/widget/MiGrid.js
    - public/javascripts/Imits/widget/MiPlanEditor.js
    - public/javascripts/Imits/widget/GeneGrid.js
    - public/javascripts/Imits/widget/MiPlansGrid.js
