---
- Aar2
- Aatk
- Abca6
- Abcc8
- Ablim3
- Acan
- Acat1
- Acot1
- Acvr1
- Adam17
- Adamts15
- Adh7
- Agbl2
- Ahr
- Alg3
- Ammecr1
- Ank2
- Ank3
- Ano1
- Arap1
- Arhgef11
- Arid4a
- Asah1
- Aspm
- Asxl2
- Atp1a3
- Atp6v1a
- Atp7a
- Banf1
- Bcan
- Bckdk
- Bclaf1
- Birc6
- Bmp1
- Bmper
- Bricd5
- Bsdc1
- Cad
- Cby1
- Ccdc22
- Ccdc91
- Cd320
- Cdc16
- Cdc42bpa
- Cdh1
- Cdh18
- Cdh2
- Cdk20
- Cep85l
- Cep97
- Cer1
- Chd4
- Chic2
- Chrnb4
- Chst2
- Cib1
- Clcc1
- Clk2
- Cnga2
- Cnnm1
- Col4a5
- Col4a6
- Col5a1
- Col9a2
- Coro1b
- Cplx1
- Creld1
- Csmd1
- Csmd3
- Csnk1d
- Cst11
- Ctgf
- Dagla
- Dcaf12l2
- Dchs1
- Deptor
- Dhx38
- Dnmt1
- Dnpep
- Dstyk
- Duox2
- E2f6
- Efnb3
- Eid2
- Eml2
- Esco1
- Ewsr1
- Eya1
- Fam122c
- Fam151a
- Fam210a
- Fasn
- Fat3
- Fat4
- Fdft1
- Fgd1
- Fgf15
- Fgfr1
- Fgfr2
- Fgr
- Flrt1
- Flt3
- Fosl1
- Foxf1
- Foxk2
- Foxp3
- Foxp4
- Frmpd1
- Fsd1l
- Fuk
- Fuz
- Fxr1
- Gatad2a
- Gdap1
- Gjc1
- Glis3
- Glrx3
- Gprasp2
- Gprc5a
- Grin2a
- Grk2
- Grm7
- Gspt2
- Gucy2c
- Hapln4
- Helz
- Herc1
- Hivep1
- Hivep2
- Hk3
- Hkdc1
- Hps3
- Ifih1
- Ift81
- Igf1r
- Igf2bp2
- Igfbp4
- Igfn1
- Ikbkg
- Il12rb1
- Info not available
- Info not available
- Info not available
- Info not available
- Info not available
- Info not available
- Info not available
- Info not available
- Info not available
- Info not available
- Info not available
- Info not available
- Info not available
- Info not available
- Info not available
- Info not available
- Info not available
- Info not available
- Info not available
- Info not available
- Info not available
- Info not available
- Info not available
- Info not available
- Info not available
- Ints6l
- Isl1
- Itga2
- Itga7
- Itga8
- Itih5
- Itpr2
- Jag1
- Jarid2
- Jmjd6
- Jup
- Kat6a
- Kcnj10
- Kcnj2
- Kcnma1
- Kcnq1
- Kctd19
- Kdm2b
- Kdm5a
- Kdm5b
- Kif22
- Kif5b
- Klhl15
- Klhl33
- Kmt2d
- Krt8
- Lama3
- Lama5
- Lbr
- Lemd2
- Lgr4
- Lingo4
- Lrp4
- Lrsam1
- Ltbp1
- Luc7l
- Lyst
- Maged2
- Magi3
- Mcm10
- Mcrs1
- Mctp2
- Meaf6
- Mecp2
- Med12
- Med16
- Mical1
- Mid1
- Mllt1
- Mogat1
- Mpi
- Mpp4
- Mprip
- Mrpl22
- Mvd
- Mxra8
- Myb
- Mybpc2
- Mylk
- Myo7a
- Myo9a
- Myom2
- Myt1
- N4bp1
- Ncapg2
- Ncoa5
- Ndufs1
- Nebl
- Nek1
- Nemf
- Nf1
- Nfatc4
- Nipbl
- Nlrp12
- Nmt1
- Nop14
- Nos2
- Notch1
- Notch2
- Nox1
- Nr2f2
- Nr3c1
- Nrd1
- Nrxn3
- Nub1
- Ocrl
- Ofd1
- Oit3
- P2rx1
- P2ry6
- Pcdh20
- Pcdhga2
- Pcdhga7
- Pcnx3
- Pcsk6
- Pdia4
- Pfas
- Pfdn1
- Phlda3
- Piezo1
- Pigt
- Pik3c2b
- Pkd1l1
- Pla2g4f
- Plcg1
- Plcg2
- Plekhg4
- Plekhm1
- Plk3
- Plrg1
- Plxnb1
- Plxnb3
- Pnma3
- Pnpla8
- Polr1b
- Polr3d
- Ppfia3
- Prex2
- Prickle1
- Prkdc
- Pth2r
- Ptpn11
- Ptpra
- Qars
- Rab11fip1
- Rac1
- Rai1
- Rai2
- Rapgef5
- Rbm8a
- Rbmx
- Reln
- Rhbdf1
- Rhobtb3
- Rnf123
- Rock1
- Rock2
- Ror1
- Ros1
- Rps6kc1
- Rsrc2
- Sall1
- Sdcbp2
- Sgpp1
- Sh2b1
- Slc18a2
- Slc24a4
- Slc30a7
- Slc39a13
- Slc7a3
- Slco6c1
- Slco6d1
- Smad5
- Smad7
- Smarca1
- Smg7
- Smo
- Smurf1
- Snx16
- Sorl1
- Sox5
- Sparcl1
- Spata3
- Spats1
- Speg
- Spry2
- Sptbn5
- Srr
- Ss18l1
- Stab1
- Stat1
- Stk32b
- Stx3
- Stxbp1
- Svil
- Syn3
- Syne2
- Sytl2
- Sytl3
- Tbc1d9
- Tbx20
- Tbx3
- Tbx4
- Tbx6
- Tchhl1
- Tenm4
- Tjp1
- Tjp3
- Tlk2
- Tlr7
- Tmem47
- Tnfrsf13b
- Trappc11
- Trib3
- Tspan32
- Tsr2
- Tub
- Tymp
- Ube2b
- Ubqln1
- Ufsp2
- Unc13b
- Usp11
- Usp19
- Usp44
- Usp53
- Vars2
- Vps13b
- Vps18
- Vps8
- Vrk1
- Wdr35
- Wdr45
- Wdr5
- Wfdc2
- Wfs1
- Xkrx
- Xylt1
- Ythdf3
- Zbtb24
- Zbtb7b
- Zdbf2
- Zdhhc23
- Zeb2
- Zfp30
- Zfp467
- Zfpm2
- Zgrf1
- Zzef1