---
- 2700049A03Rik
- Aars
- Abca4
- Abcb11
- Abcb4
- Abcc9
- Abcd2
- Abhd12
- Abhd5
- Abl1
- Aco2
- Acss2
- Acta1
- Acta2
- Actc1
- Actg2
- Actn2
- Adam10
- Adat3
- Adcy1
- Adcy6
- Adgrg1
- Adgrl3
- Agpat3
- Agrn
- Agtr1b
- Ahdc1
- Ahi1
- Aifm1
- Aimp1
- Aipl1
- Aldh18a1
- Aldh3a2
- Aldh7a1
- Aldob
- Alg1
- Alg11
- Alg13
- Alg2
- Alg3
- Alg8
- Alms1
- Aloxe3
- Als2cl
- Ankfy1
- Ankrd1
- Ankrd11
- Ano5
- Antxr1
- Ap1s2
- Ap2s1
- Ap4e1
- Apc
- Appl2
- Arap3
- Arhgef10
- Arid1b
- Arih1
- Armc4
- Armc9
- Arsa
- Arx
- Asb6
- Ash1l
- Asns
- Aspm
- Asxl1
- Asxl3
- Atad3a
- Atf6
- Atm
- Atoh7
- Atp11c
- Atp1a2
- Atp2b3
- Atp8b1
- Atpaf2
- Atr
- Atrx
- Auts2
- B3galnt2
- B9d1
- Bag3
- Bbs1
- Bbs12
- Bbs2
- Bbs5
- Bcl11b
- Bcor
- Best1
- Bicd2
- Bloc1s6
- Bmp2k
- Braf
- Brca1
- Bsnd
- C1ra
- C1rb
- C1s1
- C1s2
- C2cd3
- Cabp2
- Camk2b
- Camsap1
- Cant1
- Capn3
- Car12
- Card11
- Card14
- Carmil2
- Cask
- Casp1
- Cav1
- Cav3
- Cbl
- Cc2d2a
- Ccdc160
- Ccl2
- Ccno
- Ccr2
- Cd27
- Cd40lg
- Cdc42
- Cdh1
- Cdh23
- Cdk13
- Cdkl5
- Cenpj
- Cep290
- Cerkl
- Cftr
- Chd7
- Chd9
- Chrdl1
- Chrng
- Cib2
- Clcn1
- Clcn2
- Clcnka
- Clcnka
- Clcnkb
- Cln6
- Clp1
- Clpp
- Cnga3
- Cngb1
- Cnot3
- Cntn3
- Cntrob
- Col11a2
- Col1a1
- Col1a2
- Col27a1
- Col2a1
- Col3a1
- Col5a1
- Col6a1
- Col6a2
- Col6a3
- Col7a1
- Col9a2
- Col9a3
- Comp
- Copa
- Coro1a
- Cradd
- Crb1
- Creb3l1
- Crebbp
- Crlf1
- Crlf2
- Crx
- Cryaa
- Cspg4
- Cspp1
- Ctla4
- Ctnnb1
- Ctnnd1
- Ctr9
- Ctsa
- Cwf19l1
- Cyb5r3
- Cybb
- Cyp1b1
- Cyp26b1
- Cyp27a1
- Cyp2u1
- Dcdc2a
- Dclre1c
- Dcx
- Ddx3x
- Ddx41
- Deaf1
- Degs1
- Dgke
- Dhx30
- Dhx37
- Diaph1
- Dicer1
- Dkc1
- Dmd
- Dnm1l
- Dnm2
- Dock6
- Dock8
- Dpagt1
- Dsg2
- Dsp
- Dspp
- Duox2
- Dvl1
- Dvl3
- Dym
- Dync1h1
- Dync2h1
- Dync2li1
- Dysf
- Ebf3
- Ecel1
- Ednrb
- Efl1
- Eftud2
- Egfl6
- Ehmt1
- Elf4
- Emc1
- Eogt
- Ep300
- Epha8
- Ephb3
- Erbb3
- Ercc2
- Ercc3
- Ercc4
- Ercc5
- Ercc6
- Esrrb
- Evc
- Evc2
- Ext1
- Ext2
- Eya1
- Fam126a
- Fam83a
- Fancc
- Fars2
- Fastkd2
- Fat4
- Fbn1
- Fbn2
- Fbxl4
- Fermt1
- Fgfr1
- Fgfr3
- Fhl1
- Fig4
- Fktn
- Flnb
- Fmn2
- Foxe1
- Foxe3
- Foxg1
- Foxp1
- Fras1
- Frem1
- Fst
- Fuca1
- Fyco1
- Fzd3
- G6pc3
- Gabrb2
- Galc
- Galnt3
- Galt
- Gan
- Gas2l2
- Gata6
- Gbe1
- Gdf11
- Get4
- Gfm1
- Gfpt1
- Gins4
- Gipc3
- Gjb1
- Gjb2
- Gldc
- Gle1
- Gli2
- Gli3
- Gmnn
- Gmppa
- Gnb1
- Gnb5
- Gpihbp1
- Gpr161
- Gpsm2
- Grid2
- Grik4
- Grin1
- Grin2a
- Grin2b
- Grk2
- Grxcr1
- Gsk3a
- Gtpbp3
- Gucy1a3
- Gucy1b3
- Gucy2e
- Hars2
- Hdac8
- Herc1
- Herc2
- Hesx1
- Hexb
- Hibch
- Hira
- Hk1
- Hmgn1
- Hmox1
- Hnf1b
- Hnrnpk
- Hoxb1
- Hoxd13
- Hps1
- Hps3
- Hps4
- Hps6
- Hras
- Hsd11b2
- Hsd3b7
- Hspg2
- Hydin
- Hyls1
- Ick
- Ids
- Ier3ip1
- Ifitm5
- Ifngr2
- Ift140
- Ift43
- Ift52
- Ift80
- Ift81
- Igbp1
- Ighmbp2
- Igsf1
- Il2rg
- Il7r
- Ildr1
- Info not available
- Info not available
- Info not available
- Info not available
- Info not available
- Info not available
- Info not available
- Info not available
- Info not available
- Info not available
- Info not available
- Info not available
- Info not available
- Info not available
- Info not available
- Info not available
- Info not available
- Info not available
- Info not available
- Info not available
- Info not available
- Info not available
- Info not available
- Info not available
- Info not available
- Info not available
- Info not available
- Info not available
- Info not available
- Info not available
- Info not available
- Info not available
- Info not available
- Info not available
- Info not available
- Info not available
- Info not available
- Info not available
- Info not available
- Info not available
- Info not available
- Info not available
- Info not available
- Info not available
- Info not available
- Info not available
- Info not available
- Info not available
- Info not available
- Info not available
- Info not available
- Info not available
- Info not available
- Info not available
- Info not available
- Info not available
- Info not available
- Info not available
- Inpp5e
- Inppl1
- Ins2
- Intu
- Iqsec2
- Irf3
- Irf8
- Itgb4
- Itgb6
- Itpr1
- Jag1
- Jak3
- Jup
- Kansl1
- Kars
- Kat6a
- Kat6b
- Kcnd3
- Kcnq2
- Kcnq4
- Kctd1
- Kdm1a
- Kdm6b
- Kif11
- Kif4
- Kitl
- Kmt2a
- Kmt2c
- Kmt2d
- Kras
- Kremen1
- Krt1
- Krt25
- Krt40
- Ksr2
- L1cam
- Lama1
- Lama2
- Lama3
- Lama4
- Lama5
- Lamb2
- Lamb3
- Larp7
- Lars
- Lars2
- Lats2
- Lbr
- Ldb3
- Lhfpl5
- Lias
- Lifr
- Liph
- Lox
- Lrp2
- Lrp4
- Lrp6
- Ltbp3
- Lztr1
- Mab21l2
- Macf1
- Maf
- Mag
- Magel2
- Magt1
- Map2k1
- Map3k1
- Mapk8ip1
- Mars
- Marveld2
- Matn3
- Mboat7
- Mbtps2
- Mc1r
- Mc4r
- Mchr1
- Mcm8
- Mcm9
- Me3
- Mecp2
- Mecr
- Med25
- Mef2c
- Mertk
- Mfn2
- Mfsd8
- Mgat2
- Mipep
- Mks1
- Mlc1
- Mlycd
- Mogs
- Mplkip
- Mpz
- Msh3
- Mtm1
- Mybpc3
- Myh11
- Myh14
- Myh3
- Myh6
- Myh7
- Myh7b
- Myh9
- Mylpf
- Myo15
- Myo18b
- Myo5a
- Myo5b
- Myo7a
- Mypn
- Myrf
- Ncl
- Ncoa3
- Ncstn
- Ndrg1
- Neb
- Nebl
- Nectin4
- Nek1
- Nf1
- Nfix
- Nfkb1
- Nfkb2
- Ngly1
- Nipbl
- Nlrp6
- Nlrx1
- Nmt1
- Nobox
- Nod2
- Notch1
- Notch2
- Notch3
- Npas2
- Nphp1
- Nphp3
- Nphp4
- Nphs1
- Npr2
- Nr1d2
- Nr1h4
- Nr2e3
- Nr2f1
- Nsd1
- Nsdhl
- Ntrk1
- Nudcd2
- Nudcd3
- Obsl1
- Oca2
- Ofd1
- Ogdhl
- Olfr648
- Opa1
- Optn
- Otoa
- Otof
- Otog
- Otogl
- Otx1
- Pank2
- Pard3
- Pax2
- Pax3
- Pax9
- Pcdh15
- Pcdh19
- Pcdhga1
- Pclo
- Pcnt
- Pcyt1a
- Pde4dip
- Pde6a
- Pex1
- Pex10
- Pfdn1
- Pgap1
- Pgm2
- Pgm3
- Phf6
- Phgdh
- Phyh
- Pi4ka
- Pibf1
- Piezo2
- Pik3cd
- Pik3r4
- Pitx1
- Pitx2
- Pkd1
- Pkhd1
- Pkp1
- Pkp2
- Pla2g6
- Plcb1
- Plce1
- Plec
- Pln
- Plxnb3
- Pmm2
- Pmp2
- Pmpca
- Pnkp
- Pnpla1
- Pnpo
- Pnpt1
- Poc1b
- Pogz
- Pold1
- Polr1c
- Polr3a
- Pomt1
- Pomt2
- Porcn
- Ppox
- Ppp1cb
- Ppt1
- Prdm1
- Prdm6
- Prf1
- Prkcd
- Prkg1
- Prom1
- Prpf31
- Prpf8
- Prph2
- Prrc2c
- Prrt2
- Prune1
- Psap
- Psd3
- Psen1
- Psmc3ip
- Psmd12
- Ptch1
- Ptdss1
- Ptpn11
- Ptprq
- Pura
- Pycr1
- Pycr2
- Qars
- Rab27a
- Rab28
- Rad21
- Raf1
- Rag1
- Rapsn
- Rars
- Rasal1
- Rbfox2
- Rbm20
- Rdh11
- Rdh5
- Reln
- Rest
- Ret
- Rgs9
- Rho
- Rin2
- Ripk4
- Ripply2
- Rnf113a1
- Rnf168
- Rnf20
- Rnf213
- Robo4
- Rp1
- Rp1l1
- Rpgr
- Rpgrip1
- Rpgrip1l
- Rpl38
- Rpl5
- Rps26
- Rps28
- Rps6ka3
- Rs1
- Rsph1
- Rtel1
- Rttn
- Ryr1
- Ryr3
- S1pr2
- Sacs
- Sag
- Sall1
- Samd9l
- Sars2
- Satb2
- Sbds
- Scarf2
- Scn11a
- Scn1a
- Scn1b
- Scn2a
- Scn5a
- Scnn1b
- Serpinf1
- Setbp1
- Setd1b
- Setx
- Sf3b4
- Sgcd
- Sh2d1a
- Sh3tc2
- Sigirr
- Sigmar1
- Sin3b
- Six1
- Six2
- Ski
- Slc12a1
- Slc12a3
- Slc13a5
- Slc19a3
- Slc1a4
- Slc24a5
- Slc25a16
- Slc26a2
- Slc26a3
- Slc26a4
- Slc27a5
- Slc35a1
- Slc35a2
- Slc37a4
- Slc39a14
- Slc39a8
- Slc52a2
- Smad2
- Smad4
- Smarca2
- Smarca4
- Smarcal1
- Smarcb1
- Smarce1
- Smc1a
- Smc3
- Smchd1
- Smpd4
- Snx14
- Sohlh1
- Son
- Sos1
- Sos2
- Sost
- Sox10
- Sox9
- Spata5
- Spata7
- Spg11
- Spink5
- Spr
- Spta1
- Sptbn2
- Sptbn4
- Sptlc3
- Srcap
- Srd5a3
- Srpx2
- Ssr3
- Ssr4
- St14
- St3gal1
- Stac3
- Stat2
- Stat3
- Stub1
- Stxbp1
- Stxbp2
- Surf1
- Syne1
- Syngap1
- Syp
- Tacr3
- Taf1
- Taf6
- Taldo1
- Tango2
- Tbc1d24
- Tbc1d32
- Tbcd
- Tbck
- Tbx1
- Tbx4
- Tbx6
- Tcf4
- Tcirg1
- Tctex1d2
- Tctn1
- Tctn2
- Tecta
- Telo2
- Tg
- Tgfb1
- Tgfb2
- Tgfb3
- Tgfbr1
- Tgm1
- Thbs1
- Thoc2
- Thrb
- Tjp2
- Tlk2
- Tln1
- Tm4sf20
- Tmc1
- Tmco1
- Tmem165
- Tmem237
- Tmem67
- Tmie
- Tmpo
- Tmprss3
- Tmtc4
- Tnfrsf13b
- Tnni2
- Tnni3
- Tnxb
- Toe1
- Togaram1
- Tpm1
- Tpm2
- Tpte
- Traf3ip1
- Trank1
- Trappc11
- Trim2
- Trim32
- Trim63
- Trip12
- Trpm1
- Trpm5
- Trpv3
- Trpv4
- Trrap
- Tshr
- Ttc21b
- Ttc39a
- Ttc7
- Ttc8
- Ttn
- Tuba1a
- Tubb2b
- Tubb3
- Tubg1
- Tusc3
- Tyr
- Ube2o
- Ube3b
- Ubtf
- Unc80
- Usb1
- Ush1c
- Ush1g
- Ush2a
- Vars
- Vcan
- Vcl
- Vldlr
- Vps11
- Vps13b
- Vps13c
- Vps33b
- Vps37a
- Vrk1
- Was
- Wdr19
- Wdr34
- Wdr35
- Wdr4
- Wdr45
- Wdr60
- Wdr62
- Wdr72
- Wdr73
- Wdr90
- Wfdc2
- Whrn
- Wnt10a
- Wwox
- Xrcc4
- Xylt1
- Yars
- Zap70
- Zbtb20
- Zbtb41
- Zc4h2
- Zeb2
- Zfp335
- Zfp407
- Zfp423
- Zfyve16
- Zic3
- Zswim6