---
- Adck2
- Adck5
- Adgra1
- Adgrb2
- Adgrb3
- Adgrd1
- Adgre1
- Adgrf1
- Adgrf2
- Adgrf3
- Adgrf4
- Adgrf5
- Adgrg2
- Adgrg3
- Adgrg5
- Adgrg7
- Adgrl3
- Alpk2
- Alpk3
- Asic4
- Asic5
- Avpr1b
- Bckdk
- C130060K24Rik
- Cacna1f
- Cacna2d1
- Cacna2d2
- Cacna2d3
- Cacna2d4
- Cacnb1
- Cacnb2
- Cacnb3
- Cacnb4
- Cacng1
- Cacng3
- Cacng4
- Cacng5
- Cacng6
- Cacng7
- Cacng8
- Camk1d
- Camk1g
- Camkk1
- Camkv
- Catsper2
- Catsper4
- Cdc42bpb
- Cdc42bpg
- Cdk10
- Cdk11b
- Cdk14
- Cdk15
- Cdk17
- Cdk18
- Cdkl1
- Cdkl2
- Cdkl3
- Cdkl4
- Celsr2
- Chrm5
- Chrna10
- Chrna2
- Chrna9
- Chrnb1
- Chrnb2
- Chrnd
- Chrng
- Clca2
- Clca3a2
- Clca4a
- Clca4b
- Clcc1
- Clcn6
- Clcnka
- Clcnkb
- Clic3
- Clic5
- Clic6
- Clk3
- Clk4
- Cnga4
- Csnk1g1
- Csnk1g2
- Csnk1g3
- Csnk2a2
- Dgkh
- Dyrk1b
- Dyrk2
- Dyrk3
- Dyrk4
- Eef2k
- Ern2
- Fam26d
- Fam26e
- Fam26f
- Fastk
- Ffar3
- Fxyd3
- Fxyd7
- Fzd10
- Gabra5
- Gabra6
- Gabrb1
- Gabrg1
- Gabrg3
- Gabrp
- Gabrr1
- Gabrr3
- Gk2
- Glra3
- Glra4
- Glrb
- Gm42420
- Gpr101
- Gpr12
- Gpr135
- Gpr137
- Gpr139
- Gpr141
- Gpr142
- Gpr143
- Gpr146
- Gpr149
- Gpr150
- Gpr151
- Gpr152
- Gpr153
- Gpr156
- Gpr157
- Gpr160
- Gpr162
- Gpr171
- Gpr173
- Gpr174
- Gpr18
- Gpr19
- Gpr20
- Gpr21
- Gpr22
- Gpr25
- Gpr26
- Gpr27
- Gpr31b
- Gpr33
- Gpr34
- Gpr39
- Gpr4
- Gpr45
- Gpr6
- Gpr61
- Gpr62
- Gpr63
- Gpr75
- Gpr82
- Gpr85
- Gpr87
- Gpr88
- Gpr89
- Gprc5a
- Gprc5b
- Gprc5c
- Gprc5d
- Grid1
- Grik3
- Hcar1
- Hcar2
- Hcn3
- Hipk4
- Htr3b
- Htr5a
- Itpk1
- Itpka
- Itpr2
- Kcna6
- Kcna7
- Kcnab2
- Kcnab3
- Kcnc4
- Kcnd1
- Kcng2
- Kcng3
- Kcng4
- Kcnh4
- Kcnh6
- Kcnh7
- Kcnh8
- Kcnip1
- Kcnip4
- Kcnj14
- Kcnj15
- Kcnk12
- Kcnk16
- Kcnk4
- Kcnk7
- Kcnmb3
- Kcnmb4
- Kcnn1
- Kcns1
- Kcns2
- Kcnt1
- Kcnv1
- Lmtk3
- Lpar6
- Lrrc38
- Lrrc52
- Lrrc55
- Lrrk1
- Ltk
- Map3k10
- Map3k14
- Mapk15
- Mapk4
- Mark4
- Mast2
- Mast3
- Mast4
- Mknk2
- Mrgpra1
- Mrgpra2a
- Mrgpra2b
- Mrgpra3
- Mrgpra4
- Mrgpra6
- Mrgpra9
- Mrgprb1
- Mrgprb2
- Mrgprb3
- Mrgprb4
- Mrgprb5
- Mrgprb8
- Mrgpre
- Mrgprg
- Mrgprx1
- Mrgprx2
- Mtnr1a
- Nek10
- Nek11
- Nek4
- Nek5
- Nek6
- Nek7
- Nim1k
- Npbwr1
- Npy2r
- Npy5r
- Nrbp2
- Nrk
- Opn1mw
- Oxgr1
- P2ry10
- Pak3
- Pak6
- Pank3
- Panx2
- Panx3
- Pdik1l
- Phka1
- Phkg1
- Phkg2
- Pi4ka
- Pik3c2b
- Pik3c2g
- Pip4k2c
- Pip5k1a
- Pip5k1b
- Pkd1l3
- Pkd2l2
- Pkmyt1
- Pkn3
- Plk5
- Pllp
- Pnck
- Pomk
- Prkab1
- Prkaca
- Prkacb
- Prkag1
- Prkcq
- Prkra
- Prokr1
- Prpf4b
- Pskh1
- Pxk
- Qrfpr
- Riok1
- Riok3
- Rps6kc1
- Rps6kl1
- Rrh
- Rxfp3
- Rxfp4
- S1pr4
- Sbk2
- Sbk3
- Scn2b
- Scn3b
- Scn7a
- Scnn1b
- Scyl1
- Scyl2
- Scyl3
- Slc26a1
- Srpk3
- Sstr4
- Stk3
- Stk31
- Stk32a
- Stk32b
- Stk32c
- Stk33
- Stk36
- Stk38l
- Stk40
- Stkld1
- Sucnr1
- Taar2
- Taar8a
- Taar8b
- Taar8c
- Taar9
- Tas2r102
- Tas2r103
- Tas2r104
- Tas2r105
- Tas2r106
- Tas2r107
- Tas2r108
- Tas2r109
- Tas2r110
- Tas2r113
- Tas2r114
- Tas2r115
- Tas2r116
- Tas2r117
- Tas2r118
- Tas2r119
- Tas2r120
- Tas2r121
- Tas2r123
- Tas2r124
- Tas2r125
- Tas2r126
- Tas2r129
- Tas2r130
- Tas2r131
- Tas2r135
- Tas2r136
- Tas2r137
- Tas2r139
- Tas2r140
- Tas2r144
- Tbck
- Tesk1
- Tesk2
- Tk2
- Tlk1
- Tlk2
- Tmc3
- Tmc4
- Tmc5
- Tmc7
- Tmem38b
- Tpk1
- Tpra1
- Trp53rka
- Trp53rkb
- Tssk1
- Tssk3
- Tssk4
- Tssk6
- Ttbk1
- Ttbk2
- Ttyh1
- Ttyh2
- Uck1
- Uck2
- Ulk4
- Vmn1r233
- Vmn1r234
- Vmn1r235
- Vmn1r236
- Vmn1r237
- Vrk2
- Wee2
- nk2