--- 
- Poteg
- Adck1
- Ano7
- Ano8
- AQP10
- Bai3
- BEST4
- Bmp2k
- Brsk1
- C230081A13Rik
- Xcr1
- Cdk19
- Cdk3-ps
- Clcn6
- CLIC2
- CMKLR2
- EMR2
- EMR3
- ETBRLP2
- FCNCA
- FKSG79
- FKSG80
- FPRL2
- Fzd8
- Galr3
- Gja10
- GJA6P
- GJB7
- Gjc3
- Gje1
- Gm4776
- Gm4922
- Gm7168
- GNRHRII
- GPCR111
- Gpr113
- Gpr12
- Gpr124
- Gpr144
- Gpr15
- Gpr25
- GPR32
- Gpr39
- Gpr52
- Gpr61
- Npbwr1
- GPR78
- GPR8
- Gpr82
- GRK7
- HTR3C
- HTR3D
- HTR3E
- Kcnb2
- Kcnc3
- Kcng2
- KCNJ18
- Kcns2
- Mast1
- Mast4
- Mlkl
- Mrgprb2
- Mrgprb1
- Mrgpra1
- Mrgprx1
- Nek5
- Nim1
- Npffr1
- Npffr2
- Nr1d2
- Nr2e3
- Obscn
- Gpr68
- P2ry10
- P2Y3L
- P2Y8
- Plk5
- PRKY
- Riok1
- Rxfp3
- Sbk2
- Scn2b
- SCNN1D
- Gm1078
- Sgk2
- Sgk3
- Smok2b
- Smok3a
- Smok4a
- Gpr27
- Gpr173
- Srpk1
- STK17A
- Stk32b
- Stk36
- Tas2r119
- Tas2r110
- Tas2r114
- Tas2r116
- Tas2r103
- Tas2r139
- Tas2r107
- T2R45
- Tas2r136
- T2R48
- Tas2r105
- T2R51
- T2R52
- T2R53
- T2R54
- Tas2r131
- Tas2r120
- Tas2r126
- Tas2r135
- Tas2r121
- Tas2r102
- Tas2r105
- Taar8a
- TG1019
- Tssk6
- Ulk3
- Vrk1
- Wee2
- Wnk3
- Pkd2l2
- Kcnj9
- Gpr22
- Tpcn2
- Gpr133
- Nek10
- Panx3
- Pnck
- Kcnc2
- Mas1
- Panx2
- P2ry13
- Fastk
- Kcnk18
- Clic6
- Gpr50
- Gpr20
- Chrna9
- Limk2
- Stk16
- Lpar6
- Htr3b
- Tnik
- Stk32a
- Pth2r
- Kcnv2
- Scn3b
- Aatk
- Csnk1g3
- Bai1
- Pdk3
- Mast2
- Glra4
- Cdk14
- Nek3
- Cdc42bpa
- Nek9
- Gprc5b
- Gpr116
- Gpr35
- Gpr88
- Gpr34
- Gpr162
- Adck3
- Gpr63
- Mcoln2
- Nuak1
- Ulk4
- Gprc6a
- Map3k15
- Lphn3
- Gpr75
- Lpar5
- Oxgr1
- Kcng4
- Gpr18
- Ano9
- Gpr21
- Catsper4
- Gpr30
- Csnk1g1
- Ulk2
- Kcnu1
- Kcnj14
- Grid1
- Gjc2
- Gpr176
- Kcnk12
- Kcnh5
- Mcoln3
- S1pr4
- Gpr84
- Gpr112
- Hnf4g
- Chrm5
- Kcnk13
- Gpr65
- D8Ertd82e
- Srpk3
- Gucy2g
- Lmtk3
- Epha6
- Riok2
- Sucnr1
- Stk33
- Ano2
- Stradb
- Dyrk3
- Csnk1g2
- Nr2c1
- Bckdk
- Dstyk
- Best3
- Rxfp4
- Adck2
- BC030499
- Rps6kl1
- Mrgpre
- Phkg2
- Epha10
- Adck5
- Myo3b
- Pkn3
- Cdkl4
- Gjd4
- Gsg2
- Nek11
- Gpr110
- Stk32c
- Vrk2
- Gpr156
- Dyrk4
- Hipk4
- Ano5
- Rrh
- Cdk16
- Cdc42bpb
- Kcns3
- Kcnk16
- Rps6ka6
- Clk4
- Stk31
- Gpr45
- Tesk1
- Vrk3
- Tssk3
- Gpr125
- Csnk1d
- Clic3
- Aak1
- Gpr101
- Cdk10
- Mast3
- Esrrb
- Aqp11
- Hipk1
- Cdk12
- Stk35
- Lpar4
- Gpr183
- Gjb4
- Tpcn1
- Gjd3
- Aqp12
- Aqp12
- Gpr87
- Gpr150
- Ano4
- Gpr139
- Prkacb
- Gjb5
- Chrm4
- Tas2r138
- Map3k6
- Pak7
- Tssk4
- Tssk4
- Camkv
- Nr2f6
- S1pr5
- Gpr62
- Pak6
- Cdc42bpg
- Dyrk2
- Kcna7
- A530099J19Rik
- Gpr6
- Kcns1
- Cdkl3
- Gpr126
- Map3k9
- 4930444A02Rik
- Nuak2
- Kcna10
- Kcnj16
- Gpr85
- Mapk15
- Trib1
- Kcnj15
- Cdk17
- Mrgprd
- Abl2
- Clic5
- Nr2c2
- Nr2e1
- Lgr4
- Pskh1
- Riok3
- Camk1g
- Catsper2
- Mark4
- Irak2
- Gpr146
- Tnk1
- Sik2
- Lmtk2
- Qrfpr
- Dclk2
- Gpr19
- Gpr128
- Stk17b
- Asic4
- Nrbp2
- Mrgprg
- Mylk4
- Camk1d
- Myo3a
- Gpr171
- C5ar2
- Rorb
- Ano3
- Gpr115
- Phkg1
- Gpr4
- Tex14
- Cngb3
- Snrk
- Gpr123
- Ffar2
- Trib2
- Nrbp1
- Mknk2
- Nek7
- Tlk1
- Ticrr
- Best2
- Srpk2
- Nalcn
- Gpr153
- Tesk2
- Trp53rk
- Bai2
- BC021891
- Gm711
- Gpr114
- Acvr1c
- Ano10
- Gpr64
- Clk2
- Emr4
- Kcng3
- Clic4
- Catsper3
- Cdk18
- Tbck
- Adck4
- Catsper1
- Pdik1l
- Clk3
- Prkch
