summary_month_by_month:
  BaSH:
    2012:
      12:
        mi_goals: 588
        gc_goals: 221
      11:
        mi_goals: 560
        gc_goals: 207
      10:
        mi_goals: 532
        gc_goals: 192
      9:
        mi_goals: 502
        gc_goals: 178
      8:
        mi_goals: 474
        gc_goals: 164
      7:
        mi_goals: 442
        gc_goals: 150
      6:
        mi_goals: 414
        gc_goals: 126
      5:
        mi_goals: 384
        gc_goals: 102
      4:
        mi_goals: 356
        gc_goals: 78
      3:
        mi_goals: 328
        gc_goals: 56
      2:
        mi_goals: 300
        gc_goals: 34
      1:
        mi_goals: 252
        gc_goals: 16

    2011:
      12:
        mi_goals: 204
        gc_goals: 0
      11:
        mi_goals: 156
        gc_goals: 0
      10:
        mi_goals: 112
        gc_goals: 0
      9:
        mi_goals: 68
        gc_goals: 0
      8:
        mi_goals: 32
        gc_goals: 0
      7:
        mi_goals: 10
        gc_goals: 0
      6:
        mi_goals: 10
        gc_goals: 0


  DTCC:
    2012:
      12:
        mi_goals: 491
        gc_goals: 265
      11:
        mi_goals: 459
        gc_goals: 249
      10:
        mi_goals: 427
        gc_goals: 233
      9:
        mi_goals: 395
        gc_goals: 217
      8:
        mi_goals: 363
        gc_goals: 201
      7:
        mi_goals: 331
        gc_goals: 185
      6:
        mi_goals: 299
        gc_goals: 169
      5:
        mi_goals: 276
        gc_goals: 156
      4:
        mi_goals: 253
        gc_goals: 143
      3:
        mi_goals: 230
        gc_goals: 130
      2:
        mi_goals: 207
        gc_goals: 117
      1:
        mi_goals: 184
        gc_goals: 104

    2011:
      12:
        mi_goals: 161
        gc_goals: 91
      11:
        mi_goals: 138
        gc_goals: 78
      10:
        mi_goals: 115
        gc_goals: 65
      9:
        mi_goals: 92
        gc_goals: 52
      8:
        mi_goals: 69
        gc_goals: 39
      7:
        mi_goals: 46
        gc_goals: 26
      6:
        mi_goals: 23
        gc_goals: 13


  JAX:
    2012:
      12:
        mi_goals: 212
        gc_goals: 77
      11:
        mi_goals: 182
        gc_goals: 64
      10:
        mi_goals: 154
        gc_goals: 56
      9:
        mi_goals: 131
        gc_goals: 46
      8:
        mi_goals: 125
        gc_goals: 28
      7:
        mi_goals: 119
        gc_goals: 0
      6:
        mi_goals: 98
        gc_goals: 0
      5:
        mi_goals: 86
        gc_goals: 0
      4:
        mi_goals: 71
        gc_goals: 0
      3:
        mi_goals: 43
        gc_goals: 0
      2:
        mi_goals: 14
        gc_goals: 0
      1:
        mi_goals: 6
        gc_goals: 0

    2011:
      12:
        mi_goals: 0
        gc_goals: 0
      11:
        mi_goals: 0
        gc_goals: 0
      10:
        mi_goals: 0
        gc_goals: 0
      9:
        mi_goals: 0
        gc_goals: 0
      8:
        mi_goals: 0
        gc_goals: 0
      7:
        mi_goals: 0
        gc_goals: 0
      6:
        mi_goals: 0
        gc_goals: 0



