---
development:
  targ_rep_url: http://localhost:3000/targ_rep
  index_proxy:
    gene: http://ikmc.vm.bytemark.co.uk:8983/solr/gene
    allele: http://localhost:8983/solr/allele
    allele2: http://localhost:8983/solr/allele2
    allele21: http://ikmc.vm.bytemark.co.uk:8985/solr/allele2

test:
  targ_rep_url: https://www.i-dcc.org/imits/targ_rep
  index_proxy:
    gene: http://ikmc.vm.bytemark.co.uk:8983/solr/gene
    allele: http://localhost:8984/solr/allele
    allele2: http://localhost:8984/solr/allele2

labs:
  targ_rep_url: https://www.i-dcc.org/labs/imits/targ_rep
  index_proxy:
    gene: http://ikmc.vm.bytemark.co.uk:8983/solr/gene
    allele: http://t87-dev.internal.sanger.ac.uk:8983/solr/allele
    allele2: http://ikmc.vm.bytemark.co.uk:8985/solr/allele2

migration:
  targ_rep_url: https://www.i-dcc.org/imits/targ_rep
  index_proxy:
    gene: http://ikmc.vm.bytemark.co.uk:8983/solr/gene
    allele: http://t87-dev.internal.sanger.ac.uk:8983/solr/allele
    allele2: http://ikmc.vm.bytemark.co.uk:8985/solr/allele2

staging:
  targ_rep_url: https://www.i-dcc.org/staging/imits/targ_rep
  index_proxy:
    gene: http://ikmc.vm.bytemark.co.uk:8983/solr/gene
    allele: http://ikmc.vm.bytemark.co.uk:8984/solr/allele
    allele2: http://ikmc.vm.bytemark.co.uk:8985/solr/allele2

production:
  targ_rep_url: https://www.i-dcc.org/imits/targ_rep
  index_proxy:
    gene: http://ikmc.vm.bytemark.co.uk:8983/solr/gene
    allele: http://ikmc.vm.bytemark.co.uk:8983/solr/allele
    allele2: http://ikmc.vm.bytemark.co.uk:8985/solr/allele2

all:
  queue_run_limit: 100
