---
development:
  targ_rep_url: http://localhost:3000/targ_rep
  index_proxy:
    gene: http://ikmc.vm.bytemark.co.uk:8983/solr/gene
    allele: http://localhost:8983/solr/allele
    ck: http://localhost:8983/solr/ck
    ck2: http://ikmc.vm.bytemark.co.uk:8985/solr/ck

test:
  targ_rep_url: https://www.i-dcc.org/imits/targ_rep
  index_proxy:
    gene: http://ikmc.vm.bytemark.co.uk:8983/solr/gene
    allele: http://localhost:8984/solr/allele
    ck: http://localhost:8984/solr/ck

labs:
  targ_rep_url: https://www.i-dcc.org/labs/imits/targ_rep
  index_proxy:
    gene: http://ikmc.vm.bytemark.co.uk:8983/solr/gene
    allele: http://t87-dev.internal.sanger.ac.uk:8983/solr/allele
    ck: http://ikmc.vm.bytemark.co.uk:8985/solr/ck

migration:
  targ_rep_url: https://www.i-dcc.org/imits/targ_rep
  index_proxy:
    gene: http://ikmc.vm.bytemark.co.uk:8983/solr/gene
    allele: http://t87-dev.internal.sanger.ac.uk:8983/solr/allele
    ck: http://ikmc.vm.bytemark.co.uk:8985/solr/ck

staging:
  targ_rep_url: https://www.i-dcc.org/staging/imits/targ_rep
  index_proxy:
    gene: http://ikmc.vm.bytemark.co.uk:8983/solr/gene
    allele: http://ikmc.vm.bytemark.co.uk:8984/solr/allele
    ck: http://ikmc.vm.bytemark.co.uk:8985/solr/ck

production:
  targ_rep_url: https://www.i-dcc.org/imits/targ_rep
  index_proxy:
    gene: http://ikmc.vm.bytemark.co.uk:8983/solr/gene
    allele: http://ikmc.vm.bytemark.co.uk:8983/solr/allele
    ck: http://ikmc.vm.bytemark.co.uk:8985/solr/ck

all:
  queue_run_limit: 100
