---
development:
  targ_rep_url: http://localhost:3000/targ_rep
  user: solradmin
  password: xpassword
  index_proxy:
    gene: http://localhost:8983/solr/gene
    allele: http://localhost:8983/solr/allele
    allele2: http://ikmc.vm.bytemark.co.uk:8984/solr/allele2
    product: http://ikmc.vm.bytemark.co.uk:8984/solr/product
    eucommtoolscre_allele2: http://ikmc.vm.bytemark.co.uk:8984/solr/eucommtoolscre_allele2
    eucommtoolscre_product: http://ikmc.vm.bytemark.co.uk:8984/solr/eucommtoolscre_product

test:
  targ_rep_url: https://www.i-dcc.org/imits/targ_rep
  user: solradmin
  password: xpassword
  index_proxy:
    gene: http://ikmc.vm.bytemark.co.uk:8983/solr/gene
    allele: http://localhost:8984/solr/allele
    allele2: http://localhost:8984/solr/allele2
    product: http://localhost:8984/solr/product
    eucommtoolscre_allele2: http://localhost:8984/solr/eucommtoolscre_allele2
    eucommtoolscre_product: http://localhost:8984/solr/eucommtoolscre_product

labs:
  targ_rep_url: https://www.i-dcc.org/labs/imits/targ_rep
  user: solradmin
  password: xpassword
  index_proxy:
    gene: http://ikmc.vm.bytemark.co.uk:8983/solr/gene
    allele: http://t87-dev.internal.sanger.ac.uk:8983/solr/allele
    allele2: http://ikmc.vm.bytemark.co.uk:8985/solr/allele2
    product: http://ikmc.vm.bytemark.co.uk:8985/solr/product
    eucommtoolscre_allele2: http://ikmc.vm.bytemark.co.uk:8985/solr/eucommtoolscre_allele2
    eucommtoolscre_product: http://ikmc.vm.bytemark.co.uk:8985/solr/eucommtoolscre_product

migration:
  targ_rep_url: https://www.i-dcc.org/imits/targ_rep
  user: solradmin
  password: xpassword
  index_proxy:
    gene: http://ikmc.vm.bytemark.co.uk:8983/solr/gene
    allele: http://t87-dev.internal.sanger.ac.uk:8983/solr/allele
    allele2: http://ikmc.vm.bytemark.co.uk:8985/solr/allele2
    product: http://ikmc.vm.bytemark.co.uk:8985/solr/product
    eucommtoolscre_allele2: http://ikmc.vm.bytemark.co.uk:8985/solr/eucommtoolscre_allele2
    eucommtoolscre_product: http://ikmc.vm.bytemark.co.uk:8985/solr/eucommtoolscre_product

staging:
  targ_rep_url: https://www.i-dcc.org/staging/imits/targ_rep
  user: solradmin
  password: xpassword
  index_proxy:
    gene: http://ikmc.vm.bytemark.co.uk:8983/solr/gene
    allele: http://ikmc.vm.bytemark.co.uk:8984/solr/allele
    allele2: http://ikmc.vm.bytemark.co.uk:8984/solr/allele2
    product: http://ikmc.vm.bytemark.co.uk:8984/solr/product
    eucommtoolscre_allele2: http://ikmc.vm.bytemark.co.uk:8984/solr/eucommtoolscre_allele2
    eucommtoolscre_product: http://ikmc.vm.bytemark.co.uk:8984/solr/eucommtoolscre_product

production:
  targ_rep_url: https://www.i-dcc.org/imits/targ_rep
  user: solradmin
  password: xpassword
  index_proxy:
    gene: http://ikmc.vm.bytemark.co.uk:8983/solr/gene
    allele: http://ikmc.vm.bytemark.co.uk:8983/solr/allele
    allele2: http://ikmc.vm.bytemark.co.uk:8983/solr/allele2
    product: http://ikmc.vm.bytemark.co.uk:8983/solr/product
    eucommtoolscre_allele2: http://ikmc.vm.bytemark.co.uk:8983/solr/eucommtoolscre_allele2
    eucommtoolscre_product: http://ikmc.vm.bytemark.co.uk:8983/solr/eucommtoolscre_product

all:
  queue_run_limit: 100
