---

mi_attempts_sql : |
  select * from solr_mi_attempts;

allele_sql : |
  select * from solr_alleles;

genes_sql : |
  select * from solr_genes;

phenotype_attempts_sql : |
  select * from solr_phenotype_attempts;
