#NewIntermediateReportSummaryByGene::Generate.cache
NewIntermediateReportSummaryByMiPlan::Generate.cache
NewIntermediateReportSummaryByCentreAndConsortia::Generate.cache
NewIntermediateReportSummaryByConsortia::Generate.cache
NewIntermediateReportSummaryByCentre::Generate.cache