#!/usr/bin/env ruby

gem 'test-unit'

rails_root = File.expand_path(File.dirname(__FILE__) + '/..')
test_root = rails_root + '/test'

$LOAD_PATH << rails_root << test_root

require 'test/unit'

exit Test::Unit::AutoRunner.run(true, rails_root)
