-- http://www.postgresql.org/message-id/14658.1175879477@sss.pgh.pa.us
SET client_min_messages=WARNING;

--drop TYPE if exists solr_pa_in_progress_type cascade;
--drop TYPE if exists solr_in_progress_type cascade;
drop view if exists solr_mi_attempts cascade;
drop TABLE if exists solr_phenotype_attempts cascade;
drop view if exists solr_alleles cascade;
drop table if exists solr_genes cascade;
drop table if exists solr_gene_statuses cascade;
drop FUNCTION if exists solr_get_pa_allele_type (in int) cascade;
drop FUNCTION if exists solr_get_pa_allele_name (in int) cascade;
drop FUNCTION if exists solr_get_pa_get_order_from_urls (in int) cascade;
drop FUNCTION if exists solr_get_pa_order_from_names (in int) cascade;
drop FUNCTION if exists get_best_status_pa(a int, b boolean) cascade;
drop FUNCTION if exists solr_get_best_status_pa_cre (in int, b boolean) cascade;
drop FUNCTION if exists solr_get_mi_allele_name (in int) cascade;
drop FUNCTION if exists solr_get_mi_order_from_names (in int) cascade;
drop FUNCTION if exists solr_get_mi_order_from_urls (in int) cascade;
drop table if exists solr_centre_map cascade;
drop FUNCTION if exists solr_get_allele_order_from_names(in int) cascade;
drop FUNCTION if exists solr_get_allele_order_from_urls(in int) cascade;
drop table if exists solr_temp_projects cascade;
drop table if exists solr_ikmc_projects_details_es_cells_intermediate cascade;
drop table if exists solr_ikmc_projects_details_agg cascade;
drop table if exists solr_ikmc_projects_details_vectors_intermediate CASCADE;
drop table if exists solr_ikmc_projects_details_all CASCADE;
drop table if exists solr_ikmc_projects_details_es_cells CASCADE;
drop table if exists solr_ikmc_projects_details_vectors CASCADE;
--drop FUNCTION if exists solr_in_progress_type_mi_attempt_id(solr_in_progress_type) cascade;
--drop function if exists solr_in_progress_type_mi_plan_id(solr_in_progress_type) cascade;
drop table if exists solr_mi_attempts_in_progress_date cascade;
--drop OPERATOR CLASS if exists solr_in_progress_type_ops USING btree cascade;
--drop OPERATOR FAMILY if exists solr_in_progress_type_operator_family USING btree cascade;
--drop FUNCTION if exists solr_in_progress_type_cmp(t1 solr_in_progress_type, t2 solr_in_progress_type) CASCADE;
--drop FUNCTION if exists solr_pa_in_progress_type_phenotype_attempt_id(solr_pa_in_progress_type) cascade;
--drop function if exists solr_pa_in_progress_type_mi_plan_id(solr_pa_in_progress_type) cascade;
drop table if exists solr_pa_in_progress_date cascade;
--drop OPERATOR CLASS if exists solr_pa_in_progress_type_ops USING btree cascade;
--drop OPERATOR FAMILY if exists solr_pa_in_progress_type_operator_family USING btree cascade;
--drop FUNCTION if exists solr_pa_in_progress_type_cmp(t1 solr_pa_in_progress_type, t2 solr_pa_in_progress_type) CASCADE;
drop table if exists solr_mi_plans_relevant_status_stamp_table cascade;
drop table if exists solr_latest_relevant_mi_attempt_table cascade;
drop FUNCTION if exists solr_mi_plans_relevant_status_stamp_builder() CASCADE;
drop FUNCTION if exists solr_latest_relevant_mi_attempt_builder() CASCADE;
drop FUNCTION if exists solr_log(text) cascade;
